export type TeamMember = {
  name: string;
  role: string;
  department: string;
  experience: number; // years
  degrees: string[];
  licenses: string[];
  specialization: string;
};

export const teamMembers: TeamMember[] = [
  {
    name: "Chandrakanta Sitaula",
    role: "Managing Director & Senior Partner",
    department: "Leadership",
    experience: 25,
    degrees: ["B.Com (TU)", "MBA – Finance (PU)"],
    licenses: ["Chartered Accountant – ICAN", "Certified Public Accountant (CPA)"],
    specialization: "Statutory audit, corporate governance, and financial restructuring for large enterprises.",
  },
  {
    name: "Ramesh Prasad Adhikari",
    role: "Senior Audit Partner",
    department: "Audit & Assurance",
    experience: 22,
    degrees: ["B.Com (TU)", "M.Com – Accounting (TU)"],
    licenses: ["Chartered Accountant – ICAN", "Registered Auditor – ICAN"],
    specialization: "Statutory and internal audits for manufacturing, trading, and NGO sectors.",
  },
  {
    name: "Sunita Karmacharya",
    role: "Head of Taxation",
    department: "Taxation",
    experience: 18,
    degrees: ["BBA – Finance (KU)", "MBS – Tax Law (TU)"],
    licenses: ["Tax Agent – IRD Nepal", "Certified Tax Practitioner – ICAN"],
    specialization: "Corporate income tax planning, VAT compliance, and IRD audit defense.",
  },
  {
    name: "Bikash Tamang",
    role: "Senior Tax Consultant",
    department: "Taxation",
    experience: 12,
    degrees: ["BBA (TU)", "MBA – Taxation (PU)"],
    licenses: ["Tax Agent – IRD Nepal"],
    specialization: "Income tax returns, TDS compliance, and tax dispute resolution.",
  },
  {
    name: "Priya Shrestha",
    role: "Audit Manager",
    department: "Audit & Assurance",
    experience: 10,
    degrees: ["B.Com (TU)", "CA Finalist – ICAN"],
    licenses: ["Associate Member – ICAN"],
    specialization: "Internal control reviews and risk-based auditing for financial institutions.",
  },
  {
    name: "Deepak Raj Poudel",
    role: "Financial Consultant",
    department: "Financial Advisory",
    experience: 20,
    degrees: ["BBS (TU)", "MBA – Corporate Finance (KU)"],
    licenses: ["Certified Financial Planner – CFP Nepal", "Registered Investment Advisor – SEBON"],
    specialization: "Business valuation, feasibility studies, and investment advisory for SMEs.",
  },
  {
    name: "Anita Maharjan",
    role: "Chief Accountant",
    department: "Accounting",
    experience: 15,
    degrees: ["B.Com (TU)", "M.Com (TU)"],
    licenses: ["Registered Member – ICAN"],
    specialization: "Financial reporting under NFRS, bookkeeping systems setup, and payroll management.",
  },
  {
    name: "Sanjay Kumar Yadav",
    role: "Business Registration Specialist",
    department: "Compliance",
    experience: 8,
    degrees: ["BBA – Law & Management (PU)", "LLB (TU)"],
    licenses: ["Advocate – Nepal Bar Association", "Registered Agent – OCR Nepal"],
    specialization: "Company incorporation, OCR filings, and regulatory compliance for startups.",
  },
  {
    name: "Meena Thapa",
    role: "Accounts Manager",
    department: "Accounting",
    experience: 9,
    degrees: ["BBS (TU)", "MBS – Accounting (TU)"],
    licenses: ["Associate Member – ICAN"],
    specialization: "Day-to-day bookkeeping, bank reconciliation, and accounts payable/receivable.",
  },
  {
    name: "Roshan Bahadur Khadka",
    role: "Senior Financial Analyst",
    department: "Financial Advisory",
    experience: 7,
    degrees: ["BBA – Finance (KU)", "CFA Level II Candidate"],
    licenses: ["Associate Member – CFA Institute"],
    specialization: "Financial modeling, cash flow forecasting, and project finance analysis.",
  },
  {
    name: "Nisha Gurung",
    role: "Tax Compliance Officer",
    department: "Taxation",
    experience: 6,
    degrees: ["BBS (TU)", "Post-Graduate Diploma in Taxation – ICAN"],
    licenses: ["Tax Agent – IRD Nepal"],
    specialization: "Monthly VAT filings, excise duty compliance, and e-TDS submissions.",
  },
  {
    name: "Prakash Bhattarai",
    role: "Payroll & HR Accounts Specialist",
    department: "Accounting",
    experience: 11,
    degrees: ["BBA – HRM (PU)", "M.Sc. – Finance (TU)"],
    licenses: ["Certified Payroll Professional – NHRAN"],
    specialization: "Payroll processing, PF/CIT compliance, and labor law-aligned HR accounting.",
  },
  {
    name: "Kamala Subedi",
    role: "Audit Associate",
    department: "Audit & Assurance",
    experience: 5,
    degrees: ["B.Com (TU)", "CA Inter – ICAN"],
    licenses: ["Student Member – ICAN"],
    specialization: "Vouching, ledger verification, and supporting statutory audit engagements.",
  },
  {
    name: "Suresh Lal Shrestha",
    role: "Corporate Law Advisor",
    department: "Compliance",
    experience: 23,
    degrees: ["LLB (TU)", "LLM – Corporate Law (KU)"],
    licenses: ["Senior Advocate – Nepal Bar Association"],
    specialization: "Corporate legal structuring, contract review, and regulatory dispute advisory.",
  },
  {
    name: "Binita Sthapit",
    role: "NFRS Reporting Specialist",
    department: "Financial Advisory",
    experience: 8,
    degrees: ["B.Com (TU)", "Post-Graduate Certificate in NFRS – ICAN"],
    licenses: ["Registered Member – ICAN"],
    specialization: "Nepal Financial Reporting Standards adoption, restatement, and disclosures.",
  },
  {
    name: "Arun Basnet",
    role: "IT Audit & Systems Consultant",
    department: "Audit & Assurance",
    experience: 13,
    degrees: ["B.Sc. – IT (TU)", "MBA – Finance (PU)"],
    licenses: ["Certified Information Systems Auditor – CISA", "Associate Member – ICAN"],
    specialization: "IT general controls, ERP audit trails, and digital accounting system reviews.",
  },
  {
    name: "Sarita Limbu",
    role: "Tax Analyst",
    department: "Taxation",
    experience: 5,
    degrees: ["BBS (TU)", "Diploma in Taxation – NUTA"],
    licenses: ["Tax Agent – IRD Nepal"],
    specialization: "Individual and partnership income tax returns, withholding tax compliance.",
  },
  {
    name: "Mohan Prasad Rijal",
    role: "Senior Accounting Consultant",
    department: "Accounting",
    experience: 17,
    degrees: ["M.Com – Accounting (TU)"],
    licenses: ["Chartered Accountant – ICAN", "Registered Auditor – ICAN"],
    specialization: "Chart of accounts design, financial statement preparation, and ERP implementation support.",
  },
  {
    name: "Dipika Chaudhary",
    role: "Compliance & Regulatory Officer",
    department: "Compliance",
    experience: 7,
    degrees: ["BBA – Finance (PU)", "Post-Graduate Diploma in Compliance – ICAN"],
    licenses: ["Registered Agent – OCR Nepal", "Member – Compliance Professionals Nepal"],
    specialization: "Annual compliances, ROC filings, AGM documentation, and regulatory reporting.",
  },
  {
    name: "Tribhuvan Dhakal",
    role: "Junior Audit Associate",
    department: "Audit & Assurance",
    experience: 3,
    degrees: ["B.Com (TU)"],
    licenses: ["CA Articleship – ICAN"],
    specialization: "Audit sampling, physical verification, and working paper documentation.",
  },
];
